# content.properties - Metadata for the content package and its dependencies
# The name of this content package
name=${project.artifactId}

# The version of this content package (must follow SemVer)
version=${project.version}

# Frontend dependencies
spa.frontendModules.@clinicemr/esm-patient-payment-manager-app = 1.x
spa.frontendModules.@clinicemr/esm-patient-lab-request-form-app = 1.x

# Backend dependencies
# omod.billing = >= 2.3
